# Generated by Django 3.1 on 2020-08-14 09:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_uerdet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('price', models.IntegerField(blank=True)),
                ('category', models.CharField(max_length=128)),
                ('subcategory', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=128)),
                ('discription', models.CharField(max_length=10000)),
                ('status', models.CharField(max_length=128)),
                ('discount', models.IntegerField(blank=True)),
                ('picture', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('specifications', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('uploaded_date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Soldproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('delivery_status', models.CharField(max_length=128)),
                ('delivery_type', models.CharField(max_length=128)),
                ('odered_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.uerdet')),
            ],
        ),
    ]
