# Generated by Django 3.1 on 2020-08-14 09:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
