# Generated by Django 3.1 on 2020-08-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200814_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specifications',
            new_name='prod_spec',
        ),
    ]
