# Generated by Django 3.1 on 2020-08-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_spec',
        ),
    ]
