# Generated by Django 3.1 on 2020-08-15 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uerdet'),
        ('products', '0005_remove_product_prod_spec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=10000)),
                ('review_reply', models.CharField(blank=True, max_length=10000)),
                ('ratings', models.IntegerField(blank=True)),
                ('added_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.uerdet')),
            ],
        ),
    ]
