# Generated by Django 3.1 on 2020-08-20 09:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cart_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldproduct',
            old_name='quantity',
            new_name='Total',
        ),
        migrations.RemoveField(
            model_name='soldproduct',
            name='product_id',
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='products',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
