# Generated by Django 3.1 on 2020-08-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200820_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='deliverid',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
