# Generated by Django 3.1 on 2020-08-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_soldproduct_deliverid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldproduct',
            old_name='Total',
            new_name='total',
        ),
    ]
