# Generated by Django 3.1 on 2020-10-01 09:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uerdet'),
        ('products', '0012_auto_20200820_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeedit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainheader', models.CharField(blank=True, max_length=10000)),
                ('maintext', models.CharField(blank=True, max_length=10000)),
                ('bottomtext', models.CharField(blank=True, max_length=10000)),
                ('picture', models.CharField(blank=True, max_length=10000)),
                ('trend', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('seller', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('feature', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='total',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.uerdet'),
        ),
    ]
