# Generated by Django 3.1 on 2020-10-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201011_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='solid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.soldproduct'),
        ),
    ]
