# Generated by Django 3.1 on 2020-10-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_cart_solid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldproduct',
            name='products',
        ),
    ]
