# Generated by Django 3.1 on 2020-10-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_soldproduct_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(blank=True, max_length=10000)),
                ('category', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
