# Generated by Django 3.1 on 2020-10-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationname', models.CharField(blank=True, max_length=10000)),
                ('price', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
